### ISSUE TITLE
Hot reload always on (eval on `debug` value)

### ISSUE THREAD

**Issue by ArchangelDesign** [cnizzardini/cakephp-swagger-bake#452] opened 2022-08-19 15:13 UTC
default swagger base config sets `hot reload` based on value read by `'hotReload' => \Cake\Core\Configure::read('debug'),`
which is interpreted as string `true` or `false` which both evaluate to true.

Cake reads this value as boolean
`'debug' => filter_var(env('DEBUG', false), FILTER_VALIDATE_BOOLEAN),`

When you use read-only filesystem, hot reload will not work (like in my case) and is generated during container build process.

**Comment by cnizzardini** [comment] 2022-08-19 15:23
Whoops! You want to kick up a PR for this?

**Comment by ArchangelDesign** [comment] 2022-08-23 21:55
will do, but it's not gonna be this month, trying to push stuff to production myself :)

**Comment by cnizzardini** [comment] 2022-08-23 22:13
Np, I was unable to reproduce locally so IDK.

**Comment by cnizzardini** [comment] 2022-09-16 16:12
I'm going to close this. If you want to adjust how hotReload is set then you can do that in your `swagger_bake.php` config. The default of using the value of debug seems to work for most people.

**Closed by cnizzardini** 2022-09-16 16:12 UTC
